const customerRouter = {
    route: null,
    name: null,
    title: '客户管理',
    type: 'folder', // 类型: folder, tab, view
    icon: 'el-icon-postcard',
    filePath: 'views/customer/', // 文件路径
    order: null,
    inNav: true,
    children: [{
            title: '客户列表',
            type: 'view',
            name: 'CustomerList',
            route: '/customer/list',
            filePath: 'views/customer/CustomerList.vue',
            inNav: true,
            icon: 'iconfont icon-tushuguanli',
            right: ['获取客户列表'],
        },
        {
            title: '添加客户信息',
            type: 'view',
            name: 'CustomerAdd',
            route: '/customer/add',
            filePath: 'views/customer/CustomerAdd.vue',
            inNav: true,
            icon: 'iconfont icon-tushuguanli',
            right: ['仅录入客户信息和分配'],
        },
        {
            title: '客户日志列表',
            type: 'view',
            name: 'CustomerLogList',
            route: '/customer_log/list',
            filePath: 'views/customer_log/CustomerLogList.vue',
            inNav: false,
            icon: 'iconfont icon-tushuguanli',
        },
        {
            title: '添加客户日志',
            type: 'view',
            name: 'CustomerLogAdd',
            route: '/customer_log/add',
            filePath: 'views/customer_log/CustomerLogAdd.vue',
            inNav: false,
            icon: 'iconfont icon-tushuguanli',
        },
        {
            title: '编辑客户日志',
            type: 'view',
            name: 'CustomerLogEdit',
            route: '/customer_log/:id',
            filePath: 'views/customer_log/CustomerLogEdit.vue',
            inNav: false,
            icon: 'iconfont icon-tushuguanli',
        },
        {
            title: '客户公域池',
            type: 'view',
            name: 'CustomerCommon',
            route: '/customer/common',
            filePath: 'views/customer/CustomerCommon.vue',
            inNav: true,
            right: ['公域池列表'],
            icon: 'iconfont icon-tushuguanli'
        },
        {
            title: '客户日志列表',
            type: 'view',
            name: 'CustomerLogList',
            route: '/customer/log',
            filePath: 'views/customer_log/CustomerLogLists.vue',
            inNav: true,
            right: ['获取客户日志列表'],
            icon: 'iconfont icon-tushuguanli',
        },
        {
            title: '待办任务',
            type: 'view',
            name: 'CustomerDealtList',
            route: '/customer/dealt',
            filePath: 'views/customer/CustomerDealtLists.vue',
            inNav: true,
            right: ['获取客户待办列表'],
            icon: 'iconfont icon-tushuguanli',
        },
        {
            title: '客户信息回收站',
            type: 'view',
            name: 'CustomerRecycleList',
            route: '/setting/cRecyclelist',
            filePath: 'views/setting/CustomerRecycleList.vue',
            inNav: true,
            icon: 'iconfont icon-tushuguanli',
            right: ['恢复客户信息'],
        },
    ]
}

export default customerRouter